"""
Django settings for blog_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-pn8km*u63sq0vro9et6-n&on+-u^e#(qp8i3p)t#331zxk!ot8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Dodaję framework "sites", który jest wymagany przez allauth
    'django.contrib.sites',
    # Dodaję główne aplikacje allauth do mojego projektu
    'allauth',
    'allauth.account',
    'blog',  # nasza nowa aplikacja
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Dodaję middleware z allauth, aby obsługiwał specyficzne żądania związane z kontami
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'blog_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'blog_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'



# Ustawiam ID mojej strony, co jest absolutnie wymagane przez aplikację "sites" i allauth
SITE_ID = 1

# Konfiguruję backendy autentykacji, aby móc logować się standardowo w Django oraz przez allauth
AUTHENTICATION_BACKENDS = [
    # Standardowe logowanie w panelu admina Django
    'django.contrib.auth.backends.ModelBackend',
    # Specyficzne metody uwierzytelniania allauth (np. logowanie adresem e-mail)
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Definiuję, gdzie aplikacja ma mnie przekierować po udanym zalogowaniu
# Zmienimy to później na nazwę widoku strony głównej, na razie przekierowuję na główny adres
LOGIN_REDIRECT_URL = '/'

# Konfiguruję, aby allauth nie wymagał weryfikacji e-mail przy rejestracji (dla uproszczenia w fazie developmentu)
ACCOUNT_EMAIL_VERIFICATION = 'none'