"""Dodanie systemu tagow

Revision ID: 82bc0951623f
Revises: 2447467647d8
Create Date: 2026-07-13 20:39:55.759812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bc0951623f'
down_revision: Union[str, Sequence[str], None] = '2447467647d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tagi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nazwa', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nazwa')
    )
    op.create_table('zadanie_tag',
    sa.Column('zadanie_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tagi.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zadanie_id'], ['zadania.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('zadanie_id', 'tag_id')
    )
    op.add_column('zadania', sa.Column('data_utworzenia', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zadania', 'data_utworzenia')
    op.drop_table('zadanie_tag')
    op.drop_table('tagi')
    # ### end Alembic commands ###
