"""
Django settings for my_project project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from celery.schedules import crontab
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p2d823hkck2l)2lz293r^*vd05ufr3e)c-lcf5rx=zo8twrgrw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Rejestruję moją nową aplikację
    'my_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Dodaję konfigurację Celery na końcu pliku
# Ustawiam adres URL do mojego brokera wiadomości (Redis)
CELERY_BROKER_URL = 'redis://localhost:6379/0'

# Ustawiam adres URL do backendu wyników (korzystam z tego samego Redisa)
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# Ustawiam akceptowane formaty treści i serializacji na JSON
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Ustawiam polską strefę czasową
CELERY_TIMEZONE = 'Europe/Warsaw'


# Ustawienia dla Celery Beat
CELERY_BEAT_SCHEDULE = {
    'zapisuj-czas-co-10-sekund': {
        'task': 'my_app.tasks.log_timestamp',  # ścieżka do Twojego zadania
        'schedule': 10.0,
    }, # wykonuj co 10 sekund
    # Nowe zadanie: uruchamiaj o 23:00 każdego dnia
    'policz-uzytkownikow-codziennie-o-23': {
        'task': 'my_app.tasks.count_users',  # Ścieżka do zadania z poprzedniego kroku
        'schedule': crontab(hour=23, minute=0),
    },
}

# Adres URL, pod którym będą widoczne pliki w przeglądarce
MEDIA_URL = '/media/'

# Fizyczna ścieżka na dysku, gdzie Django stworzy folder "media"
MEDIA_ROOT = BASE_DIR / 'media'

# Określam nazwę domyślnej kolejki, do której wpadają wszystkie "zwykłe" zadania
CELERY_TASK_DEFAULT_QUEUE = 'default'

# Definiuję specjalne trasy (routing). 
# Celery z automatu utworzy tę kolejkę w Redis, gdy tylko wyślę do niej pierwsze zadanie.
CELERY_TASK_ROUTES = {
    # Mówię: "Jeśli wywołuję zadanie 'send_priority_email' w aplikacji 'my_app', 
    # wrzuć je zawsze do kolejki 'priority_queue'"
    'my_app.tasks.send_priority_email': {'queue': 'priority_queue'},
}